# Generated by Django 5.2.6 on 2026-02-20 23:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
        ('salon', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountSupportTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('EMERGENCY', 'Emergency'), ('GENERAL', 'General')], default='GENERAL', max_length=20)),
                ('summary', models.TextField()),
                ('status', models.CharField(choices=[('NEW', 'New'), ('IN_REVIEW', 'In Review'), ('CANCELLED', 'Cancelled'), ('RESOLVED', 'Resolved')], default='NEW', max_length=20)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_queries', to='authentication.account')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_queries', to='salon.customer')),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salon_queries', to='salon.salon')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('level', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='LOW', max_length=50)),
                ('topic', models.CharField(choices=[('ACCOUNT', 'Account'), ('SALON_MANAGEMENT', 'Salon Management'), ('CHATBOTS', 'Chatbots'), ('CLIENT_REQUESTS', 'Client Requests'), ('OTHERS', 'Others')], default='OTHERS', max_length=50)),
                ('subject', models.CharField(max_length=255)),
                ('queries', models.TextField()),
                ('status', models.CharField(choices=[('NEW', 'New'), ('IN_REVIEW', 'In Review'), ('CANCELLED', 'Cancelled'), ('RESOLVED', 'Resolved')], default='NEW', max_length=20)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_tickets', to='authentication.account')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
