# Generated by Django 5.2.6 on 2026-02-28 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountsupportticket',
            name='type',
            field=models.CharField(choices=[('EMERGENCY', 'Emergency'), ('CALLBACK_REQUEST', 'Callback Request'), ('COMPLAINT', 'Complaint'), ('GENERAL_INQUIRY', 'General Inquiry'), ('SPECIAL_REQUEST', 'Special Request')], default='GENERAL_INQUIRY', max_length=20),
        ),
    ]
