# Generated by Django 5.2.6 on 2026-02-20 23:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
        ('common', '0001_initial'),
        ('salon', '0001_initial'),
        ('support', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerotp',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otps', to='salon.customer'),
        ),
        migrations.AddField(
            model_name='media',
            name='support_ticket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_ticket_images', to='support.supportticket'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_subcategories', to='authentication.account'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='common.category'),
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('account', 'name', 'category_type')},
        ),
        migrations.AddIndex(
            model_name='customerotp',
            index=models.Index(fields=['customer', 'otp_code'], name='common_cust_custome_8c4262_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='subcategory',
            unique_together={('account', 'name', 'category')},
        ),
    ]
