# Generated by Django 5.2.6 on 2026-02-20 23:15

import apps.salon.utils
import datetime
import django.contrib.gis.db.models.fields
import django.core.validators
import django.db.models.deletion
import django_countries.fields
import multiselectfield.db.fields
import phonenumber_field.modelfields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
        ('common', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(choices=[('HAIR_CARE_PRODUCTS', 'Hair Care Products'), ('SKIN_CARE_PRODUCTS', 'Skin Care Products'), ('MAKEUP_PRODUCTS', 'Makeup Products'), ('NAIL_CARE_PRODUCTS', 'Nail Care Products'), ('MENS_GROOMING_PRODUCTS', "Men's Grooming Products"), ('BODY_CARE_PRODUCTS', 'Body Care Products'), ('HAIR_REMOVAL_PRODUCTS', 'Hair Removal Products'), ('TOOLS_AND_ACCESSORIES', 'Tools & Accessories'), ('SALON_RETAIL_AND_GIFT_PRODUCTS', 'Salon Retail & Gift Products'), ('OTHER_PRODUCTS', 'Other Products')], max_length=100, unique=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(choices=[('HAIR_SERVICES', 'Hair Services'), ('HAIR_REMOVAL_SERVICES', 'Hair Removal Services'), ('BRIDAL_AND_MAKEUP_SERVICES', 'Bridal and Makeup Services'), ('MENS_GROOMING_SERVICES', "Men's Grooming Services"), ('SKIN_OR_FACIAL_SERVICES', 'Skin or Facial Services'), ('NAIL_SERVICES', 'Nail Services'), ('MESSAGE_AND_BODY_SERVICES', 'Massage and Body Services'), ('EYEBROW_AND_EYELASH_SERVICES', 'Eyebrow and Eyelash Services'), ('OTHER_SERVICES', 'Other Services')], max_length=100, unique=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductSubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('is_custom', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_categories', to='salon.productcategory')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('category', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Salon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to=apps.salon.utils.get_salon_logo_path)),
                ('name', models.CharField(max_length=255)),
                ('salon_category', models.CharField(choices=[('GENERAL_SALON', 'General Salon'), ('MOBILE_OR_HOME_SERVICE_SALON', 'Mobile or Home Service Salon'), ('OCCASIONALLY_BOTH', 'Occasionally Both')], default='GENERAL_SALON', max_length=50)),
                ('is_provide_hair_styles', models.BooleanField(default=False)),
                ('hair_service_types', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('AFRO_TEXTURED', 'Afro-textured (kinky / coily / natural hair)'), ('CURLY', 'Curly'), ('WAVY', 'Wavy'), ('STRAIGHT', 'Straight'), ('NOT_SURE', 'Not sure')], help_text='Select one or more hair service types offered by the salon.', max_length=100)),
                ('is_provide_bridal_makeup_services', models.BooleanField(default=False)),
                ('bridal_makeup_service_types', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('BRIDAL_MAKEUP', 'Bridal Makeup'), ('ENGAGEMENT_PRE_WEDDING_MAKEUP', 'Engagement / pre-wedding makeup'), ('PARTY_EVENING_MAKEUP', 'Party / evening makeup'), ('PHOTOSHOOT_EDITORIAL_MAKEUP', 'Photoshoot / editorial makeup'), ('TRADITIONAL_CULTURAL_BRIDAL_MAKEUP', 'Traditional / cultural bridal makeup'), ('HD_AIRBRUSH_MAKEUP', 'HD / airbrush makeup'), ('HAIR_STYLING_FOR_BRIDAL_CLIENTS', 'Hair styling for bridal clients'), ('GROOM_MAKEUP_GROOMING', 'Groom makeup / grooming'), ('NOT_SURE', 'Not sure')], help_text='Select one or more bridal makeup service types offered by the salon.', max_length=300)),
                ('salon_type', models.CharField(choices=[('BARBERSHOP', 'Barbershop / Men’s Salon'), ('UNISEX_SALON', 'Unisex Salon'), ('LADIES_SALON', 'Ladies Salon')], default='UNISEX_SALON', max_length=30)),
                ('additional_service_types', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('BEAUTY_SERVICES', 'Beauty services'), ('NAIL_SERVICES', 'Nail services'), ('SPA_SERVICES', 'Spa services'), ('NONE_OF_THE_ABOVE', 'None of the above')], help_text='Select one or more additional service types offered by the salon.', max_length=100)),
                ('formatted_address', models.TextField(blank=True, null=True)),
                ('google_place_id', models.CharField(blank=True, max_length=255, null=True)),
                ('latitude', models.DecimalField(decimal_places=14, max_digits=17, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)])),
                ('longitude', models.DecimalField(decimal_places=14, max_digits=18, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)])),
                ('location', django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326)),
                ('city', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=20)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('phone_number_one', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('phone_number_two', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('email', models.EmailField(max_length=254)),
                ('facebook', models.URLField(blank=True, null=True)),
                ('instagram', models.URLField(blank=True, null=True)),
                ('youtube', models.URLField(blank=True, null=True)),
                ('about_salon', models.TextField(blank=True, null=True)),
                ('professional_career_details', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=10)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_salons', to='authentication.account')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.CharField(blank=True, max_length=300, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_products', to='authentication.account')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_category', to='salon.productcategory')),
                ('sub_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='product_sub_categories', to='salon.productsubcategory')),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salon_products', to='salon.salon')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OpeningHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('day', models.CharField(choices=[('MONDAY', 'Monday'), ('TUESDAY', 'Tuesday'), ('WEDNESDAY', 'Wednesday'), ('THURSDAY', 'Thursday'), ('FRIDAY', 'Friday'), ('SATURDAY', 'Saturday'), ('SUNDAY', 'Sunday')], max_length=20)),
                ('opening_time', models.TimeField(blank=True, null=True)),
                ('closing_time', models.TimeField(blank=True, null=True)),
                ('is_closed', models.BooleanField(default=False)),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opening_hours', to='salon.salon')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee_id', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('image', models.ImageField(blank=True, null=True, upload_to=apps.salon.utils.get_salon_employee_image_path)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_employees', to='authentication.account')),
                ('designation', models.ForeignKey(limit_choices_to={'category_type': 'EMPLOYEE'}, on_delete=django.db.models.deletion.PROTECT, related_name='employee_designation', to='common.category')),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salon_employees', to='salon.salon')),
            ],
            options={
                'unique_together': {('account', 'salon', 'employee_id')},
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
                ('type', models.CharField(choices=[('LEAD', 'Lead'), ('CUSTOMER', 'Customer')], default='LEAD', max_length=20)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_customers', to='authentication.account')),
                ('source', models.ForeignKey(limit_choices_to={'category_type': 'CUSTOMER_SOURCE'}, on_delete=django.db.models.deletion.PROTECT, related_name='customer_source', to='common.category')),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salon_customers', to='salon.salon')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Chair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('MAINTENANCE', 'Maintenance'), ('OUT_OF_ORDER', 'Out of Order')], default='AVAILABLE', max_length=20)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_chairs', to='authentication.account')),
                ('type', models.ForeignKey(limit_choices_to={'category_type': 'CHAIR'}, on_delete=django.db.models.deletion.PROTECT, related_name='chair_type', to='common.category')),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salon_chairs', to='salon.salon')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking_id', models.CharField(max_length=8)),
                ('booking_date', models.DateField()),
                ('booking_time', models.TimeField()),
                ('status', models.CharField(choices=[('PLACED', 'Placed'), ('INPROGRESS', 'In-progress'), ('COMPLETED', 'Completed'), ('RESCHEDULED', 'Rescheduled'), ('CANCELLED', 'Cancelled'), ('ABSENT', 'Absent')], db_index=True, default='PLACED', max_length=15)),
                ('notes', models.TextField(blank=True, null=True)),
                ('booking_duration', models.DurationField(default=datetime.timedelta(seconds=1800))),
                ('cancellation_reason', models.TextField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('tips_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('payment_type', models.CharField(choices=[('FRONT_DESK', 'Front Desk'), ('SELF_CHECKOUT', 'Self Checkout'), ('CREDIT_CARD', 'Credit Card'), ('CASH', 'Cash'), ('CHECK', 'Check'), ('GIFT_CARD', 'Gift Card'), ('VENMO', 'Venmo'), ('OTHER', 'Other')], default='CASH', max_length=20)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_bookings', to='authentication.account')),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_cancelled_bookings', to=settings.AUTH_USER_MODEL)),
                ('chair', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chair_bookings', to='salon.chair')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_bookings', to='salon.customer')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_bookings', to='salon.employee')),
                ('products', models.ManyToManyField(blank=True, related_name='product_bookings', to='salon.product')),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salon_bookings', to='salon.salon')),
            ],
            options={
                'ordering': ['-booking_date', '-booking_time'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.CharField(blank=True, max_length=300, null=True)),
                ('service_duration', models.DurationField(default=datetime.timedelta(seconds=1800))),
                ('available_time_slots', models.JSONField(default=list, help_text="List of available time slots. Example: ['MORNING', 'AFTERNOON']", validators=[apps.salon.utils.validate_available_time_slots])),
                ('gender_specific', models.CharField(choices=[('BARBERSHOP', 'Barbershop / Men’s Salon'), ('UNISEX_SALON', 'Unisex Salon'), ('LADIES_SALON', 'Ladies Salon')], default='UNISEX_SALON', max_length=30)),
                ('discount_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_services', to='authentication.account')),
                ('assign_employees', models.ManyToManyField(blank=True, related_name='employee_services', to='salon.employee')),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salon_services', to='salon.salon')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='service_category', to='salon.servicecategory')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SalonMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to=apps.salon.utils.get_salon_media_path)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking_images', to='salon.booking')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_images', to='salon.product')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_images', to='salon.service')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='booking',
            name='services',
            field=models.ManyToManyField(related_name='service_bookings', to='salon.service'),
        ),
        migrations.CreateModel(
            name='ServiceSubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('is_custom', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_categories', to='salon.servicecategory')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='service',
            name='sub_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='service_sub_categories', to='salon.servicesubcategory'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['booking_date', 'booking_time'], name='salon_booki_booking_69b311_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['salon', 'status'], name='salon_booki_salon_i_59f4c4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='servicesubcategory',
            unique_together={('category', 'name')},
        ),
    ]
