# Generated by Django 5.2.6 on 2026-02-22 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salon',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='salon',
            name='longitude',
        ),
        migrations.AddField(
            model_name='customer',
            name='thread_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
