# Generated by Django 5.2.6 on 2026-02-22 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0002_remove_salon_latitude_remove_salon_longitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salon',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
