# Generated by Django 5.2.6 on 2026-02-25 05:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0004_alter_customer_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_duration',
            field=models.DurationField(blank=True, default=datetime.timedelta(seconds=1800), null=True),
        ),
    ]
