# Generated by Django 5.2.6 on 2026-03-16 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0005_alter_booking_booking_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='source',
            field=models.CharField(choices=[('AFROBEUTIC', 'Afrobeutic'), ('MANUAL', 'Manual'), ('WHATSAPP', 'WhatsApp')], default='MANUAL', max_length=20),
        ),
    ]
