# Generated by Django 5.2.6 on 2026-04-13 10:04

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0006_booking_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, size=None),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('CONFIRMED', 'Confirmed'), ('INPROGRESS', 'In-progress'), ('COMPLETED', 'Completed'), ('RESCHEDULED', 'Rescheduled'), ('CANCELLED', 'Cancelled'), ('NO_SHOW', 'No-Show')], db_index=True, default='CONFIRMED', max_length=15),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='name',
            field=models.CharField(choices=[('HAIR_PRODUCTS', 'Hair Products'), ('HAIR_EXTENSIONS_AND_WIGS', 'Hair Extensions & Wigs'), ('HAIR_ACCESSORIES', 'Hair Accessories'), ('SKIN_AND_BEAUTY', 'Skin & Beauty'), ('NAILS', 'Nails'), ('MENS_GROOMING', "Men's Grooming"), ('RETAIL_AND_GIFTS', 'Retail & Gifts'), ('OTHER_PRODUCTS', 'Other Products')], max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='servicecategory',
            name='name',
            field=models.CharField(choices=[('HAIR', 'Hair'), ('BEAUTY_AND_MAKEUP', 'Beauty & makeup'), ('SKIN_AND_FACIAL', 'Skin & Facial'), ('NAILS', 'Nails'), ('MENS_GROOMING', 'Mens Grooming'), ('BODY_AND_MASSAGE', 'Body & Massage'), ('HAIR_REMOVAL', 'Hair Removal'), ('OTHER', 'Other')], max_length=100, unique=True),
        ),
    ]
