# Generated by Django 5.2.6 on 2026-02-28 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Chatbot',
        ),
    ]
