# Generated by Django 5.2.6 on 2026-03-01 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        ('billing', '0002_delete_chatbot'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymentcard',
            options={},
        ),
        migrations.AddConstraint(
            model_name='paymentcard',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('account',), name='unique_default_card_per_account'),
        ),
    ]
