# Generated by Django 5.2.6 on 2026-03-03 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_alter_paymentcard_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pricingplan',
            name='broadcasting_message_limit',
        ),
        migrations.RemoveField(
            model_name='pricingplan',
            name='has_broadcasting',
        ),
    ]
