# Generated by Django 5.2.6 on 2026-03-10 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_remove_pricingplan_broadcasting_message_limit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='remaining_whatsapp_messages',
            field=models.PositiveIntegerField(default=0, help_text='Stacked remaining messages. On plan change: new_remaining = current_remaining + new_plan.total_messages'),
        ),
    ]
