# Generated by Django 5.2.6 on 2026-03-10 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_subscription_remaining_whatsapp_messages'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttransaction',
            name='attempt_number',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
